stages:
  - test
  - quality

cache:
  key: 'algoritmohistorico'
  paths:
  - node_modules/
  
test_job:
  image: registry.es.gov.br/espm/infraestrutura/containers/node:8.12.0
  stage: test
  script:
     - npm install
     - npm run test
  retry: 2   

quality_job:
  image: registry.es.gov.br/espm/infraestrutura/containers/sonar-scanner:3.3.0.1492
  stage: quality
  dependencies:
      - test_job    
  script:
   - npm install
   - npm run test:cov
   - sonar-scanner
